image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $IMAGE_TAG .
    - echo "Pushing Docker image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - ssh -o StrictHostKeyChecking=no ec2-user@13.60.17.42 "docker pull $IMAGE_TAG && docker run -d -p 80:80 $IMAGE_TAG"
  only:
    - master
